#!/bin/bash
#KESSEL title: Test 
source "$KESSEL_ROOT/share/kessel/setup-env.sh"

source "$KESSEL_BUILD_ENV"
export CTEST_OUTPUT_ON_FAILURE=1
ctest -V -S $KESSEL_CTEST_DRIVER_SCRIPT,Test,$report_errors
