#!/bin/bash
#KESSEL title: Test 
source "$KESSEL_ROOT/share/kessel/setup-env.sh"

source "$KESSEL_BUILD_ENV"
export CTEST_OUTPUT_ON_FAILURE=1
ctest --test-dir "$KESSEL_BUILD_DIR" --output-junit tests.xml
