steps:
 - name: configure
   title: Configure
   collapsed: true
   arguments:
     - argument:
         - '-I'
         - '--install-dir'
         - default: $install_dir
           help: "install directory (default: %(default)s)"
   script:
    - spack install --test root --include-build-deps -u cmake -v $project
    - kessel build-env generate --type spack
    - run: cmake -DCMAKE_VERBOSE_MAKEFILE=off -DCMAKE_INSTALL_PREFIX=$install_dir $build_dir 2> /dev/null > /dev/null
      buildenv: true
