echo "Activating deployment at ${KESSEL_DEPLOYMENT}"

export KESSEL_CURRENT_SYSTEM="${KESSEL_CURRENT_SYSTEM:-${KESSEL_SYSTEM}}"

unset SPACK_DISABLE_LOCAL_CONFIG
export SPACK_USER_CACHE_PATH="$KESSEL_DEPLOYMENT/.spack"
export SPACK_SKIP_MODULES=true
export SPACK_USER_CONFIG_PATH="$KESSEL_DEPLOYMENT/.spack"
export SPACK_SYSTEM_CONFIG_PATH="$KESSEL_CONFIG_DIR"

source "$KESSEL_DEPLOYMENT/spack/share/spack/setup-env.sh"
