#!/bin/bash

if [ -z "${ENVIRONMENTS}" ]; then
    export ENVIRONMENTS="$(kessel env list)"
fi

install_options="--include-build-deps"
buildcache_options="--with-build-dependencies"
if [ "${KESSEL_BUILD_ROOTS}" = "true" ]; then
  install_options="--only dependencies $install_options"
  buildcache_options="--only dependencies $buildcache_options"
fi

for ENVIRONMENT in ${ENVIRONMENTS}
do
  echo "Building '${ENVIRONMENT}' environment"
  kessel env activate ${ENV_DIR:-.}/${ENVIRONMENT}
  # temporarily disable view, since we're building on multiple architectures
  spack config add view:false

  # bail out if concretization takes too long
  timeout -s SIGKILL 5m spack concretize -f --fresh

  if [ $? -ne 0 ]; then
    echo "Concretization took too long (>5 min)... SKIPPING." >& 2
    continue
  fi

  spack install $install_args
  if [ -n "$KESSEL_BUILD_CACHE_MIRROR" ]; then
    spack buildcache push $buildcache_options "${KESSEL_BUILD_CACHE_MIRROR}"
  fi
done
