#!/bin/bash
kessel deploy init ${KESSEL_DEPLOYMENT_CONFIG}

if [ -n "$KESSEL_BUILD_EXCLUDE" ]; then
    for p in "${KESSEL_BUILD_EXCLUDE[@]}"
    do
        spack uninstall -y --all --dependents "$p" || true
    done
fi

spack clean -a

echo "Setting permissions and group..."
chown -R ":$KESSEL_GROUP" "$KESSEL_DEPLOYMENT"
chmod -R "$KESSEL_PERMISSIONS" "$KESSEL_DEPLOYMENT"

chmod g+s "$KESSEL_DEPLOYMENT/spack/opt/spack/.spack-db"

SQFS_FILE="$KESSEL_DEPLOYMENT/.replicate.sqfs"
"$KESSEL_ROOT/libexec/kessel/workflows/spack_deployment/gen_replicate_sqfs" "$KESSEL_DEPLOYMENT" "$SQFS_FILE"
chown ":$KESSEL_GROUP" "$SQFS_FILE"
chmod "$KESSEL_PERMISSIONS" "$SQFS_FILE"
