#!/bin/bash

export KESSEL_REQUIRE_SYSTEM_MIRROR=none
if [ "$KESSEL_SYSTEM" = "rocinante"  ] || [ "$KESSEL_SYSTEM" = "ATS3" ]; then
    export KESSEL_REQUIRE_SYSTEM_MIRROR="pe-serve"
fi

# can be removed with static git_mirrors.yaml after https://github.com/spack/spack/pull/51098
gen_git_mirrors_yaml() {
  GIT_MIRRORS_YAML="$KESSEL_DEPLOYMENT/config/git_mirrors.yaml"
  TMP_GIT_MIRRORS_YAML="$GIT_MIRRORS_YAML.$$"

  echo "packages:" > "$TMP_GIT_MIRRORS_YAML"

  printf "%s\n" "$KESSEL_GIT_MIRRORS" | while IFS= read -r p
  do
      REPO_PATH=$(git -C "${KESSEL_DEPLOYMENT}/$p" rev-parse --absolute-git-dir)
      EXT_NAME=$(basename "$p")
      cat >> "$TMP_GIT_MIRRORS_YAML" <<EOF
  ${EXT_NAME}:
    package_attributes:
      git: 'file://${REPO_PATH}'
EOF
  done

  if cmp -s $TMP_GIT_MIRRORS_YAML $GIT_MIRRORS_YAML; then
    rm -f $TMP_GIT_MIRRORS_YAML
  else
    mv $TMP_GIT_MIRRORS_YAML $GIT_MIRRORS_YAML
  fi
}

concretize_env_for_mirror() {
    env_name="$1"
    echo "Concretizing $env_name..."
    spack env activate $env_name
    rm -rf "$SPACK_ENV/.spack-env"
    mkdir -p "$SPACK_ENV/.spack-env"
    cp "$SPACK_ENV/spack.yaml" "$SPACK_ENV/spack.yaml.original"

    spack config add view:false

    spack concretize -f --fresh 2>&1 > "$SPACK_ENV/.spack-env/concretization.txt" || touch "$SPACK_ENV/.spack-env/failure" &
    spack env deactivate
}

get_env_name() {
    absolute_path=$(readlink -f "$1")
    abs_root=$(readlink -f "$2")
    realpath -s "$(dirname "$absolute_path")" | sed "s|^$abs_root/||"
}

create_env_mirror() {
    mirror_dir="$1"
    mirror_exclude_file="$2"
    env_name="$3"
    failure_file="$SPACK_ENV/.spack-env/failure"
    if [ -f "$failure_file" ]; then
        echo "ERROR: Concretization of $env_name failed!" >&2
        false
        return
    else
        echo "Creating mirror for $env_name..."
        spack env activate $env_name
        spack spec
        if [ -f "$mirror_exclude_file" ]; then
            spack mirror create -d "$mirror_dir" --all --skip-unstable-version --exclude-file "$mirror_exclude_file"
        else
            spack mirror create -d "$mirror_dir" --all --skip-unstable-version
        fi
        rm -f "$SPACK_ENV/spack.lock"
        cp "$SPACK_ENV/spack.yaml.original" "$SPACK_ENV/spack.yaml"
    fi
}

if [ -z "${ENVIRONMENTS}" ]; then
    export ENVIRONMENTS="$(spack env list | tr -d ' ')"
fi

mirror_dir="$KESSEL_DEPLOYMENT/spack-mirror"
env_dir="$KESSEL_DEPLOYMENT/environments/$KESSEL_SYSTEM"
mirror_exclude_file="$KESSEL_DEPLOYMENT/config/mirror.exclude"

if [ -n "$KESSEL_MIRROR_EXCLUDE" ]; then
    printf "%s\n" "$KESSEL_MIRROR_EXCLUDE" > "$mirror_exclude_file"
fi

if [ -n "$KESSEL_GIT_MIRRORS" ]; then
    gen_git_mirrors_yaml
fi

set +m

printf "%s\n" "$ENVIRONMENTS" | while IFS= read -r e
do
    if [ -n "${e}" ]; then
        concretize_env_for_mirror "$e"
    fi
done

wait

set -m

printf "%s\n" "$ENVIRONMENTS" | while IFS= read -r e
do
    if [ -n "${e}" ]; then
        create_env_mirror "$mirror_dir" "$mirror_exclude_file" "$e"
    fi
done

unset KESSEL_REQUIRE_SYSTEM_MIRROR
