#!/bin/bash
DEPLOYMENT_DIR="$1"
DEST="$2"
echo "Creating deployment copy..."
echo "  src: $DEPLOYMENT_DIR"
echo "  dst: $DEST"

umask u=rwx,g=rx,o=

rsync -a --no-p --no-g --chmod=ugo=rwX --exclude='.env' --exclude='/extern/*' --exclude='spack-mirror' \
      --exclude='spack-bootstrap' --exclude='/.git/modules/extern/*' \
      --exclude='/extern/*'  --exclude='/spack' --exclude='/spack-packages' --exclude='*spack.lock' \
      --exclude='*.spack-env*' \
      "$DEPLOYMENT_DIR/" "$DEST"

rsync -a --no-p --no-g --chmod=ugo=rwX --include='{*__pycache__* "*.pyc"}' \
           --include="etc/spack/**" --include="lib/spack/**" \
         --exclude-from="$DEPLOYMENT_DIR/spack/.gitignore" \
        "$DEPLOYMENT_DIR/spack/" "$DEST/spack"

rsync -a --no-p --no-g --chmod=ugo=rwX --include='{*__pycache__* "*.pyc"}' \
         --exclude-from="$DEPLOYMENT_DIR/spack-packages/.gitignore" \
        "$DEPLOYMENT_DIR/spack-packages/" "$DEST/spack-packages"

cp ${KESSEL_ROOT}/libexec/kessel/workflows/spack_deployment/activate.sh.in $DEST/activate.sh
sed -i "s#@KESSEL_PARENT_DEPLOYMENT@#$DEPLOYMENT_DIR#g" $DEST/activate.sh
sed -i "s/@KESSEL_SYSTEM@/$KESSEL_SYSTEM/g" $DEST/activate.sh
