#!/bin/bash
umask 0007
mkdir -p ${KESSEL_DEPLOYMENT}
chgrp ${KESSEL_GROUP} ${KESSEL_DEPLOYMENT} || true
chmod g+s ${KESSEL_DEPLOYMENT} || true

rm -rf "${KESSEL_DEPLOYMENT}/kessel"
git clone $KESSEL_ROOT/.git ${KESSEL_DEPLOYMENT}/kessel

source kessel/share/kessel/setup-env.sh

(
    cd ${KESSEL_DEPLOYMENT}
    kessel deploy init ${KESSEL_DEPLOYMENT_CONFIG}
    cp -R ${KESSEL_DEPLOYMENT_CONFIG}/.kessel ${KESSEL_DEPLOYMENT}/
)

kessel deploy activate "$KESSEL_DEPLOYMENT"
kessel system activate "$KESSEL_SYSTEM"

clone_and_sync() {
    src_checkout="$1"
    src=$(git -C "$1" rev-parse --absolute-git-dir)
    dest="$2"
    echo "$src -> $dest"
    $KESSEL_ROOT/libexec/kessel/tools/update_local_branches.sh "$src_checkout"
    mkdir -p $(dirname "$dest")
    rm -rf "$dest"
    git -c advice.detachedhead=false clone "$src" "$dest"
    $KESSEL_ROOT/libexec/kessel/tools/update_local_branches.sh "$dest"
}

printf "%s\n" "$KESSEL_GIT_MIRRORS" | while IFS= read -r p
do
  clone_and_sync "$KESSEL_DEPLOYMENT_CONFIG/$p" "$KESSEL_DEPLOYMENT/$p"
done
