#!/bin/bash
if [ ! -f "$KESSEL_DEPLOYMENT/.clone.sqfs" ]; then
  echo "ERROR: $KESSEL_DEPLOYMENT/.clone.sqfs does not exist!" >&2
  exit 1
fi

mkdir -p $(dirname $1)
unsquashfs -d "$1" "$KESSEL_DEPLOYMENT/.clone.sqfs"
