#!/bin/bash
#KESSEL title: Install Environment
#KESSEL collapsed: true

if [ -z "$KESSEL_SYSTEM" ] || [ -z "$KESSEL_ENVIRONMENT" ]; then
  echo "ERROR: Invalid state" >&2
  false
  return
fi

spack concretize -f
spack install --include-build-deps --only dependencies
