#!/bin/bash
#KESSEL title: Prepare Environment
#KESSEL collapsed: true

if [ -z "$KESSEL_SYSTEM" ] || [ -z "$KESSEL_PROJECT_SPEC" ]; then
  echo "ERROR: Invalid state '$KESSEL_SYSTEM' '$KESSEL_PROJECT_SPEC' " >&2
  false
  return
fi

export KESSEL_ENVIRONMENT="${KESSEL_ENVIRONMENT:-default}"
export KESSEL_SOURCE_DIR="${KESSEL_SOURCE_DIR:-$PWD}"
export KESSEL_BUILD_DIR="${KESSEL_BUILD_DIR:-$KESSEL_SOURCE_DIR/build}"

TEMP=""
while (( "$#" )); do
  case "$1" in
    -h|--help)
      usage
      true
      return
      ;;
    -e|--env)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_ENVIRONMENT="$2"
         shift 2
      else
         echo "ERROR: -S/--source-dir requires an argument." >&2
         false
         return
      fi
      ;;
    --env=*)
      value="${1#*=}"
      export KESSEL_ENVIRONMENT="$value"
      shift
      ;;
    -S|--source-dir)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_SOURCE_DIR="$2"
         shift 2
      else
         echo "ERROR: -S/--source-dir requires an argument." >&2
         false
         return
      fi
      ;;
    --source-dir=*)
      value="${1#*=}"
      export KESSEL_INSTALL_DIR="$value"
      shift
      ;;
    -B|--build-dir)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_BUILD_DIR="$2"
         shift 2
      else
         echo "ERROR: -B/--build-dir requires an argument." >&2
         false
         return
      fi
      ;;
    --build-dir=*)
      value="${1#*=}"
      export KESSEL_BUILD_DIR="$value"
      shift
      ;;
    -*|--*)
      echo "ERROR: invalid option $1" >&2
      false
      return
      ;;
    *)
      TEMP="$TEMP $1"
      shift
      ;;
  esac
done

if [ "$TEMP" ]; then
  export KESSEL_PROJECT_SPEC="$TEMP"
fi

if ! spack env activate "$KESSEL_ENVIRONMENT"; then
  if [ "$KESSEL_SYSTEM" = "local" ]; then
    spack env create "$KESSEL_ENVIRONMENT"
    spack env activate "$KESSEL_ENVIRONMENT"
    spack add "$KESSEL_PROJECT_SPEC"
    spack env activate "$KESSEL_ENVIRONMENT"
  else
    echo "ERROR: Can not activate or create environment $KESSEL_ENVIRONMENT!"
    false
    return
  fi
fi

export KESSEL_PROJECT_NAME=$(spack-python -c "spec = spack.spec.Spec('$KESSEL_PROJECT_SPEC');print(spec.name)")

if [ -d "$KESSEL_SOURCE_DIR/spack_repo/$KESSEL_PROJECT_NAME" ]; then
  spack repo remove "$KESSEL_PROJECT_NAME" 2> /dev/null > /dev/null || true
  spack repo add "$KESSEL_SOURCE_DIR/spack_repo/$KESSEL_PROJECT_NAME"
fi

spack develop -b "$KESSEL_BUILD_DIR" -p "$KESSEL_SOURCE_DIR" --no-clone "$KESSEL_PROJECT_NAME"
spack config add "packages:${KESSEL_PROJECT_NAME}:package_attributes:keep_werror:all"
