#!/bin/bash
#KESSEL title: Setup
#KESSEL collapsed: true

export KESSEL_SYSTEM="${KESSEL_SYSTEM:-local}"
export KESSEL_WORKFLOW_DEPLOYMENT="${KESSEL_WORKFLOW_DEPLOYMENT:-${TMPDIR:-/tmp}/$USER-ci-envs}"

TEMP=()
while (( "$#" )); do
  case "$1" in
    -h|--help)
      usage
      return
      ;;
    -D|--deployment)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_WORKFLOW_DEPLOYMENT="$2"
         shift 2
      else
         echo "ERROR: -I/--install-dir requires an argument." >&2
         return 1
      fi
      ;;
    --deployment=*)
      export KESSEL_WORKFLOW_DEPLOYMENT=${1#*=}
      shift
      ;;
    -s|--system)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_SYSTEM="$2"
         shift 2
      else
         echo "ERROR: -s/--system requires an argument." >&2
         return 1
      fi
      ;;
    --system=*)
      export KESSEL_SYSTEM=${1#*=}
      shift
      ;;
    -*|--*)
      echo "ERROR: invalid option $1" >&2
      return 1
      ;;
    *)
      TEMP+=("$1")
      shift
      ;;
  esac
done

umask 0007
if [[ "$KESSEL_SYSTEM" == "local" ]]; then
  if [[ -z "$SPACK_ROOT" ]]; then
    echo "ERROR: No active Spack installation!" >&2
    return 1
  else
    echo "Using Spack install at $SPACK_ROOT"
  fi
else
  if [ ! -d "$KESSEL_WORKFLOW_DEPLOYMENT" ]; then
      kessel deploy replicate "$KESSEL_WORKFLOW_DEPLOYMENT"
      kessel deploy activate "$KESSEL_WORKFLOW_DEPLOYMENT"
      kessel system activate "$KESSEL_SYSTEM"
  fi
fi
