#!/bin/bash
#KESSEL title: Setup
#KESSEL collapsed: true

export KESSEL_SOURCE_DIR="${KESSEL_SOURCE_DIR:-$PWD}"
export KESSEL_BUILD_DIR="${KESSEL_BUILD_DIR:-$PWD/build}"
export KESSEL_ENVIRONMENT="${KESSEL_ENVIRONMENT:-default}"
export KESSEL_REQUIREMENTS="${KESSEL_REQUIREMENTS:-requirements.txt}"

TEMP=()
while (( "$#" )); do
  case "$1" in
    -h|--help)
      usage
      return
      ;;
    -S|--source-dir)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_SOURCE_DIR="$2"
         shift 2
      else
         echo "ERROR: -S/--source-dir requires an argument." >&2
         return 1
      fi
      ;;
    -B|--build-dir)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_BUILD_DIR="$2"
         shift 2
      else
         echo "ERROR: -B/--build-dir requires an argument." >&2
         return 1
      fi
      ;;
    -e|--env)
      if [ -n "$2" ] && [[ "$2" != -* ]]; then
         export KESSEL_ENVIRONMENT="$2"
         shift 2
      else
         echo "ERROR: -e/--env requires an argument." >&2
         return 1
      fi
      ;;
    --source-dir=*)
      export KESSEL_SOURCE_DIR=${1#*=}
      shift
      ;;
    --build-dir=*)
      export KESSEL_BUILD_DIR=${1#*=}
      shift
      ;;
    --env=*)
      export KESSEL_ENVIRONMENT=${1#*=}
      shift
      ;;
    -*|--*)
      echo "ERROR: invalid option $1" >&2
      return 1
      ;;
    *)
      TEMP+=("$1")
      shift
      ;;
  esac
done

ENV_DIR="$KESSEL_BUILD_DIR/envs"
ENV="$ENV_DIR/$KESSEL_ENVIRONMENT"
mkdir -p "$ENV_DIR"

if [ ! -d "$ENV" ]; then
    "$KESSEL_PYTHON" -m venv "$ENV"
fi

source "$ENV/bin/activate"

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to activate environment" >&2
    return 1
fi

python3 -m pip install -r "$KESSEL_REQUIREMENTS"
deactivate

export KESSEL_BUILD_ENV=${ENV}/bin/activate
