#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 dump-file spec" >&2
  exit 1
fi

dump_file=$1
shift

spack build-env --dump "$dump_file" "$@"

# filter common batch system variables
grep -Ev '^(FLUX_|SLURM_|XPC_)' "$dump_file" > "$dump_file.tmp"
echo "PS1='(build) ${KESSEL_PARENT_PROMPT}'" >> "$dump_file.tmp"
mv "$dump_file.tmp" "$dump_file"
