name: Build and Deploy docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build:
      runs-on: ubuntu-latest
      steps:      
        - uses: actions/checkout@v4
        - name: build docs
          run: |
            source share/kessel/setup-env.sh
            kessel activate docs
            kessel run
